SystemUIGoogle: Temporary disable tiles which are not ready.
* DataSwitchTile: fixup code
vendor/pixelstyle/SystemUIGoogle/src/com/pixeldust/android/systemui/qs/tiles/DataSwitchTile.java:192: error: cannot find symbol
            int defaultPhoneId = mSubscriptionManager.getDefaultDataPhoneId();
                                                     ^
* SyncTile/VpnTile: fixup perms
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: java.lang.SecurityException: no permission to read the sync settings: Neither user 10468 nor current process has android.permission.READ_SYNC_SETTINGS.
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at android.os.Parcel.createException(Parcel.java:3041)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at android.os.Parcel.readException(Parcel.java:3024)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at android.os.Parcel.readException(Parcel.java:2966)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at android.content.IContentService$Stub$Proxy.getMasterSyncAutomatically(IContentService.java:1452)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at android.content.ContentResolver.getMasterSyncAutomatically(ContentResolver.java:3523)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at com.pixeldust.android.systemui.qs.tiles.SyncTile.handleUpdateState(SyncTile.java:100)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at com.pixeldust.android.systemui.qs.tiles.SyncTile.handleUpdateState(SyncTile.java:47)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at com.android.systemui.qs.tileimpl.QSTileImpl.handleRefreshState(QSTileImpl.java:465)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at com.android.systemui.qs.tileimpl.QSTileImpl$H.handleMessage(QSTileImpl.java:641)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at android.os.Looper.loopOnce(Looper.java:205)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at android.os.Looper.loop(Looper.java:294)
10-25 11:07:57.033  1820  1902 W Tile.SyncTile: 	at android.os.HandlerThread.run(HandlerThread.java:67)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: Error in handleRefreshState
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: java.lang.SecurityException: Requires one of the following permissions: android.permission.NETWORK_STACK, android.permission.MAINLINE_NETWORK_STACK.
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at android.os.Parcel.createException(Parcel.java:3041)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at android.os.Parcel.readException(Parcel.java:3024)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at android.os.Parcel.readException(Parcel.java:2966)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at android.net.IVpnManager$Stub$Proxy.getAllLegacyVpns(IVpnManager.java:1032)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at android.net.VpnManager.getAllLegacyVpns(VpnManager.java:727)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at com.android.systemui.statusbar.policy.SecurityControllerImpl.getConfiguredLegacyVpns(SecurityControllerImpl.java:224)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at com.pixeldust.android.systemui.qs.tiles.VpnTile.handleUpdateState(VpnTile.java:200)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at com.pixeldust.android.systemui.qs.tiles.VpnTile.handleUpdateState(VpnTile.java:64)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at com.android.systemui.qs.tileimpl.QSTileImpl.handleRefreshState(QSTileImpl.java:465)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at com.android.systemui.qs.tileimpl.QSTileImpl$H.handleMessage(QSTileImpl.java:641)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at android.os.Looper.loopOnce(Looper.java:205)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at android.os.Looper.loop(Looper.java:294)
10-25 11:07:57.035  1820  1902 W Tile.VpnTile: 	at android.os.HandlerThread.run(HandlerThread.java:67)

Signed-off-by: spezi77 <spezi7713@gmx.net>